In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier as KNC

In [5]:
dtst=pd.read_csv("C:/Users/PARCHU/Downloads/diabetes.csv")

In [6]:
train,test=train_test_split(dtst,test_size=0.2)
trainx=train.iloc[:,0:8]
trainy=train.iloc[:,8]
testx=test.iloc[:,0:8]
testy=test.iloc[:,8]

In [7]:
trainx

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
613,6,105,80,28,0,32.5,0.878,26
297,0,126,84,29,215,30.7,0.520,24
280,0,146,70,0,0,37.9,0.334,28
184,4,141,74,0,0,27.6,0.244,40
28,13,145,82,19,110,22.2,0.245,57
...,...,...,...,...,...,...,...,...
645,2,157,74,35,440,39.4,0.134,30
62,5,44,62,0,0,25.0,0.587,36
4,0,137,40,35,168,43.1,2.288,33
510,12,84,72,31,0,29.7,0.297,46
235,4,171,72,0,0,43.6,0.479,26

In [8]:
trainy

613    0
297    0
280    1
184    0
28     0
      ..
645    0
62     0
4      1
510    1
235    1
Name: Outcome, Length: 614, dtype: int64

In [11]:
hs=[]
for i in range(3,50,2):
    modelkn=KNC(n_neighbors=i)
    modelkn.fit(trainx,trainy)
    prdkn=modelkn.predict(testx)
    knac=np.mean(prdkn==testy)
    hs.append([knac,i])

In [12]:
hs

[[0.7207792207792207, 3],
 [0.7012987012987013, 5],
 [0.6948051948051948, 7],
 [0.7272727272727273, 9],
 [0.7467532467532467, 11],
 [0.7207792207792207, 13],
 [0.7272727272727273, 15],
 [0.7337662337662337, 17],
 [0.7272727272727273, 19],
 [0.7207792207792207, 21],
 [0.7532467532467533, 23],
 [0.7272727272727273, 25],
 [0.7532467532467533, 27],
 [0.7467532467532467, 29],
 [0.7532467532467533, 31],
 [0.7272727272727273, 33],
 [0.7337662337662337, 35],
 [0.7532467532467533, 37],
 [0.7402597402597403, 39],
 [0.7337662337662337, 41],
 [0.7272727272727273, 43],
 [0.7142857142857143, 45],
 [0.7207792207792207, 47],
 [0.7207792207792207, 49]]