In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeClassifier

In [2]:
dtst=pd.read_csv("C:/Users/PARCHU/Downloads/glass.csv")

In [3]:
dtst

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

In [4]:
dtst.shape

(214, 10)

In [6]:
dtst.isnull().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [5]:
target=dtst.iloc[:,9]
target

0      1
1      1
2      1
3      1
4      1
      ..
209    7
210    7
211    7
212    7
213    7
Name: Type, Length: 214, dtype: int64

In [7]:
features=dtst.iloc[:,0:9]
features

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0
..       ...    ...   ...   ...    ...   ...   ...   ...  ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0

[214 rows x 9 columns]

In [8]:
scalar=StandardScaler()
scalar.fit(features)
dt=scalar.transform(features)

In [9]:
dt

array([[ 0.87286765,  0.28495326,  1.25463857, ..., -0.14576634,
        -0.35287683, -0.5864509 ],
       [-0.24933347,  0.59181718,  0.63616803, ..., -0.79373376,
        -0.35287683, -0.5864509 ],
       [-0.72131806,  0.14993314,  0.60142249, ..., -0.82894938,
        -0.35287683, -0.5864509 ],
       ...,
       [ 0.75404635,  1.16872135, -1.86551055, ..., -0.36410319,
         2.95320036, -0.5864509 ],
       [-0.61239854,  1.19327046, -1.86551055, ..., -0.33593069,
         2.81208731, -0.5864509 ],
       [-0.41436305,  1.00915211, -1.86551055, ..., -0.23732695,
         3.01367739, -0.5864509 ]])

In [13]:
pca=PCA(n_components=2)
pca.fit(dt)
cv=pca.transform(dt)
cv

array([[ 1.15113957e+00, -5.29487638e-01],
       [-5.74137172e-01, -7.59787774e-01],
       [-9.40159722e-01, -9.29835966e-01],
       [-1.42083283e-01, -9.61677440e-01],
       [-3.51092291e-01, -1.09124921e+00],
       [-2.90266583e-01, -1.32400756e+00],
       [-2.52671444e-01, -1.11614958e+00],
       [-1.20299466e-01, -1.22184622e+00],
       [-2.08160308e-02, -3.21932609e-01],
       [-2.35222894e-03, -1.06581344e+00],
       [-3.82514937e-01, -1.38013403e+00],
       [-1.33538675e-02, -1.10471913e+00],
       [-3.09724390e-01, -1.42304024e+00],
       [ 1.56521013e-01, -1.23592823e+00],
       [-8.99566628e-02, -1.18125211e+00],
       [-1.15255023e-01, -1.16028212e+00],
       [ 1.73458320e-01, -1.18243967e+00],
       [ 1.45812372e+00,  9.88413780e-02],
       [ 5.47316267e-01, -2.95660130e-01],
       [-3.08817022e-01, -7.63162157e-01],
       [ 2.05673879e-01, -9.99182661e-01],
       [ 1.21605345e+00, -4.36896108e-01],
       [ 4.11679297e-02, -1.02788338e+00],
       [-1.13206012e-01, -1.02762181e+00],
       [-1.47523366e-01, -9.33767049e-01],
       [-5.04865218e-02, -1.04723075e+00],
       [-1.55773980e-01, -7.38149546e-01],
       [-2.17093779e-01, -1.03946718e+00],
       [-1.15093633e-01, -1.05293936e+00],
       [-6.58374915e-02, -9.02875839e-01],
       [ 2.98261451e-01, -1.16489328e+00],
       [-2.22363433e-02, -1.16273745e+00],
       [ 3.96586112e-01, -1.07307343e+00],
       [-6.90862734e-02, -1.16390421e+00],
       [ 8.17537725e-02, -9.66019429e-01],
       [-3.88918640e-01, -1.00978004e+00],
       [ 2.57422809e-01, -9.89360442e-02],
       [ 2.70430953e-02, -9.41150868e-01],
       [ 1.93311245e+00, -1.42114298e-01],
       [ 1.93311245e+00, -1.42114298e-01],
       [ 2.13978802e-01, -1.06505169e+00],
       [ 1.73653764e-02, -1.10093167e+00],
       [-9.91042449e-02, -7.46806921e-01],
       [ 1.90784649e+00, -1.35146218e-01],
       [ 7.55238909e-01, -1.19430193e+00],
       [ 4.15149070e-01, -2.93287264e-01],
       [ 6.04423395e-01, -7.80199849e-01],
       [ 2.97136159e+00,  4.63140502e-01],
       [ 2.07281161e+00, -1.93673881e-01],
       [ 3.93111591e-01, -3.40258187e-01],
       [ 2.72721095e+00, -1.13038577e-01],
       [ 7.23068883e-01, -4.74891927e-01],
       [ 1.06160451e-01, -4.14506038e-01],
       [ 1.81361046e-01, -4.09957896e-01],
       [ 1.71804895e-01, -5.10287786e-01],
       [ 4.59256767e-01, -9.72071790e-01],
       [-4.23198376e-01, -1.81655603e+00],
       [ 1.58405624e-02, -9.57454062e-01],
       [-3.27242420e-01, -1.10236197e+00],
       [ 3.73730855e-02, -1.05432062e+00],
       [ 4.57306871e-01, -5.51911400e-01],
       [ 2.36220840e-01,  5.68330203e-01],
       [ 1.88483803e+00, -2.96475700e-01],
       [ 1.90646324e+00,  1.85186825e-01],
       [ 1.76739012e+00, -2.34851172e-01],
       [ 1.20709914e+00, -1.68166022e-02],
       [ 2.09535866e+00, -4.27013874e-01],
       [ 2.06574480e+00, -4.47085324e-01],
       [ 2.00488480e+00, -3.63498656e-01],
       [ 2.25195536e+00,  2.79739773e-02],
       [-1.11062971e+00, -3.60459191e-01],
       [ 7.49344065e-01, -8.70094723e-01],
       [-9.35068761e-01, -1.20394562e+00],
       [-8.81333556e-01, -9.72313068e-01],
       [-9.22562290e-01, -1.19692928e+00],
       [-8.78041073e-01, -1.20892921e+00],
       [-6.85088615e-01, -8.41639892e-01],
       [-6.90359145e-01, -1.06629931e+00],
       [-4.62997748e-01, -9.88247287e-01],
       [-1.07450035e+00, -9.64788704e-01],
       [-1.21369799e+00, -7.79098155e-01],
       [-9.09189665e-01, -1.13899985e+00],
       [-5.35657351e-01, -1.06978417e+00],
       [-6.51404126e-01, -1.11647242e+00],
       [-2.31637606e+00, -5.73982461e-01],
       [-6.19527617e-01, -8.77061910e-01],
       [-8.67763488e-01, -1.07801813e+00],
       [-5.36304118e-01, -9.23478860e-01],
       [-6.50903533e-01, -1.06424608e+00],
       [-7.55392780e-01, -1.09926663e+00],
       [ 9.91658801e-01, -1.02189999e+00],
       [-5.62642120e-01, -1.06581042e+00],
       [-3.06796378e-01, -9.64066395e-01],
       [-7.34604026e-01, -9.22386904e-01],
       [-6.55247560e-01, -1.14303255e+00],
       [ 9.46407531e-02, -4.56164629e-01],
       [ 9.04286720e-01, -8.98187688e-01],
       [ 6.13895376e-01, -1.40234153e+00],
       [-6.54109481e-01, -7.10902736e-01],
       [-1.33583022e-01, -4.11998638e-01],
       [-2.26479128e-02, -8.10349081e-01],
       [-7.23703277e-02, -5.16663086e-01],
       [ 9.83504760e-01, -1.02010847e+00],
       [ 3.85238194e+00,  1.34506467e+00],
       [ 2.35136469e+00,  1.14019846e+00],
       [ 3.33328693e+00,  2.02616879e+00],
       [ 3.64021336e+00,  6.19344465e+00],
       [ 7.13869786e+00,  4.00443669e+00],
       [ 1.69502290e+00,  2.07414559e+00],
       [ 7.41593451e-01,  7.85341417e-01],
       [ 4.51874493e+00,  2.02772563e+00],
       [ 4.87303441e+00,  2.11110882e+00],
       [ 4.59649709e+00,  2.69944760e+00],
       [ 3.23984511e-01, -9.15170462e-01],
       [ 2.59209029e-01, -1.01845622e+00],
       [ 2.86272002e-02, -8.03704365e-01],
       [ 1.86714046e-01, -8.88809019e-01],
       [-8.34974605e-01, -5.23690716e-01],
       [-6.31138456e-02, -1.09080518e+00],
       [-6.88645250e-01, -8.44544670e-01],
       [ 9.33354363e-02, -7.97513650e-01],
       [-3.25952384e-01, -1.16131445e+00],
       [-5.72010313e-01, -9.28041764e-01],
       [-7.81415457e-01, -6.41887105e-01],
       [ 7.93041028e-01, -6.04328270e-01],
       [ 2.72746438e-01, -7.60850930e-01],
       [-1.21350033e-01, -1.06270367e+00],
       [ 1.11574391e+00,  6.20438569e-01],
       [ 6.40905488e-01,  9.00575079e-01],
       [ 1.06594039e+00,  1.36757767e+00],
       [ 1.37738839e+00,  1.60336370e+00],
       [ 3.41894371e+00,  3.13489973e+00],
       [-2.30106379e-03, -1.02447346e+00],
       [ 9.43164121e-02, -6.45011377e-01],
       [-1.20536745e-01, -1.01574215e+00],
       [ 6.14443758e-01, -1.09156288e+00],
       [ 3.37682286e-01, -1.29110463e+00],
       [-5.41321804e-01, -1.03138006e+00],
       [-7.66226327e-01, -1.21918683e+00],
       [-7.74831821e-01, -1.08145439e+00],
       [-6.58328771e-01, -7.80730458e-01],
       [ 4.79061318e-01, -1.00897795e+00],
       [-6.25511768e-02, -1.22086276e+00],
       [-7.02191754e-01, -7.51136992e-01],
       [ 3.02639624e-01, -1.04410159e+00],
       [ 9.68425776e-01, -1.14896334e+00],
       [ 1.15965177e-01, -7.37970348e-01],
       [-4.92429807e-01, -9.56241961e-01],
       [-1.66864635e-01, -9.65406470e-01],
       [-7.09007624e-02, -1.30120252e+00],
       [-3.15800764e-01, -7.53169864e-01],
       [ 1.52912927e+00,  5.44240128e-02],
       [ 5.95438880e-01, -9.54422853e-01],
       [-4.47183180e-01, -9.57421674e-01],
       [-2.28073900e-03, -9.59297592e-01],
       [-2.77448819e-01, -1.01028758e+00],
       [-2.62625463e-01, -7.71749068e-01],
       [ 1.74711568e+00, -1.83206568e-01],
       [-8.19412962e-02, -3.43555681e-01],
       [ 7.70000955e-02, -2.78969006e-01],
       [ 1.06061322e-01, -2.83081850e-01],
       [ 1.21897823e+00, -6.73372800e-01],
       [ 2.19327703e+00, -1.60194716e-01],
       [-4.32287332e+00,  2.65385680e+00],
       [ 2.60337952e-01,  5.48033322e-01],
       [ 1.80337643e+00,  5.28727703e-01],
       [ 1.78618611e+00,  3.12751888e-01],
       [ 6.83776477e-01,  1.39728332e+00],
       [-7.95024676e-01,  7.94729609e-01],
       [ 5.44543846e-01,  1.76724509e+00],
       [ 1.92981829e+00,  2.49244227e+00],
       [-4.38953460e+00, -1.03449577e-01],
       [-4.43253973e+00, -1.68680125e-01],
       [ 1.59504215e+00,  2.11331608e+00],
       [ 1.01004447e+00,  8.84077930e-01],
       [ 1.63107556e+00,  1.31861732e+00],
       [ 2.56498778e-01,  6.39225236e-01],
       [ 6.54463516e-01,  3.42545752e-01],
       [-1.99650272e-01,  7.40225310e-01],
       [-1.44389955e-01,  6.39849281e-01],
       [-2.32566823e+00, -4.62400329e-01],
       [-2.73475886e-01,  1.78882182e+00],
       [-6.68969638e-02,  2.24369392e+00],
       [ 1.11416397e+00,  1.45711253e+00],
       [-3.28279679e+00, -4.17913576e-02],
       [-3.95051181e+00, -7.28506609e-01],
       [-2.76034579e+00,  1.26705494e+00],
       [ 1.06709874e+00, -7.14334989e-02],
       [ 5.88963889e-01,  1.91167950e+00],
       [-2.17032226e-02,  3.47383505e+00],
       [-1.38770709e+00,  1.08914537e+00],
       [-2.14926480e+00,  2.29560843e+00],
       [-2.10698079e+00,  2.13071878e+00],
       [-2.08135612e+00,  3.07840526e+00],
       [-2.16116939e+00,  2.89977062e+00],
       [-2.29846438e+00,  2.21466938e+00],
       [-2.10499822e+00,  2.37404264e+00],
       [-1.95865705e+00,  2.46318823e+00],
       [-2.39038043e+00,  2.40058515e+00],
       [-2.34025986e+00,  2.43366642e+00],
       [-2.67936046e+00,  2.13082037e+00],
       [-1.37738556e+00, -8.70759297e-01],
       [-2.73231156e+00,  2.03728730e+00],
       [-2.52519849e+00,  3.12098266e+00],
       [-2.26974017e+00,  2.34831576e+00],
       [-2.04532108e+00,  3.07594965e+00],
       [-2.18787696e+00,  2.85648463e+00],
       [-3.55709771e+00,  3.46675073e+00],
       [-1.99364680e+00,  2.59939654e+00],
       [-2.38383457e+00,  3.06167702e+00],
       [-2.39765190e+00,  3.10823570e+00],
       [-1.68024627e+00,  3.28482346e+00],
       [-2.36974768e+00,  2.75687280e+00],
       [-2.26264885e+00,  3.02859155e+00]])

In [14]:
cvv=pd.DataFrame(cv)

In [15]:
cvv

            0         1
0    1.151140 -0.529488
1   -0.574137 -0.759788
2   -0.940160 -0.929836
3   -0.142083 -0.961677
4   -0.351092 -1.091249
..        ...       ...
209 -2.383835  3.061677
210 -2.397652  3.108236
211 -1.680246  3.284823
212 -2.369748  2.756873
213 -2.262649  3.028592

[214 rows x 2 columns]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(cvv,target, test_size = 0.3, random_state=1)

In [20]:
mdl=DecisionTreeClassifier(criterion='entropy')
mdl.fit(X_train,y_train)
prdict=mdl.predict(X_test)
acc=np.mean(prdict==y_test)
acc

0.5692307692307692